_ESCAPE_SEQUENCE = "^^^"
_SYSTEM_PREFIX = _ESCAPE_SEQUENCE + "SYS"
_REQUEST_PREFIX = _ESCAPE_SEQUENCE + "RQS"

CMD_DELAY_NEXT_PACKET = _SYSTEM_PREFIX + "PDL"
CMD_GET_SERIAL_NUMBER = _REQUEST_PREFIX + "SRN"
